# Generated by Django 3.0.4 on 2020-03-08 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_prbac.fields
import django_prbac.models
import jsonfield.fields
import uuid




class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The friendly name for this role to present to users; this need not be unique, but must not be blank.', max_length=256, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(help_text='The formal slug for this role, which should be unique. If not provided, it will be automatically filled.', max_length=256, unique=True, verbose_name='Slug', populate_from=["name"])),
                ('description', models.TextField(blank=True, default='', help_text='A long-form description of the intended semantics of this role.', verbose_name='Description')),
                ('parameters', django_prbac.fields.StringSetField(blank=True, default=set, help_text='A set of strings which are the parameters for this role. Entered as a JSON list.', verbose_name='Parameters')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When this item was first created.', verbose_name='DateTime Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='When this item last updated.', verbose_name='DateTime Modified')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_roles', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django_prbac.models.ValidatingModel, models.Model),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='django_prbac.Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prbac_role', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django_prbac.models.ValidatingModel, models.Model),
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', jsonfield.fields.JSONField(blank=True, default=dict, help_text='Assignment from parameters (strings) to values (any JSON-compatible value).', verbose_name='Assignment')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When this item was first created.', verbose_name='DateTime Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='When this item last updated.', verbose_name='DateTime Modified')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_grants', to=settings.AUTH_USER_MODEL)),
                ('from_role', models.ForeignKey(help_text='The sub-role begin granted membership or permission', on_delete=django.db.models.deletion.CASCADE, related_name='memberships_granted', to='django_prbac.Role')),
                ('to_role', models.ForeignKey(help_text='The super-role or permission being given', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='django_prbac.Role')),
            ],
            bases=(django_prbac.models.ValidatingModel, models.Model),
        ),
    ]
